//USER
export const LOGIN_USER = "LOGIN_USER"; // action

//JOBS
export const RECIEVED_JOBS = "RECIEVED_JOBS"; //
export const FETCH_JOBS = "FETCH_JOBS"; // <--- new
export const FILTERED_JOBS = "FILTERED_JOBS";
export const CLEAR_USER_JOB_FILTER_SELECTIONS =
  "CLEAR_USER_JOB_FILTER_SELECTIONS";

//DEGREES
export const RECIEVED_DEGREES = "RECIEVED_DEGREES"; //
export const FETCH_DEGREES = "FETCH_DEGREES"; // <--- new
export const UNIQUE_DEGREE = "UNIQUE_DEGREE"; // <--- new
export const INCLUDE_JOBS_BY_DEGREE = "INCLUDE_JOBS_BY_DEGREE"; // <--- new
export const ADD_SELECTED_JOB_DEGREE = "ADD_SELECTED_JOB_DEGREE"; // <--- new

//ORGANISATIONS
export const UNIQUE_ORGANISATIONS = "UNIQUE_ORGANISATIONS"; // <--- new
export const ADD_SELECTED_ORGANISATIONS = "ADD_SELECTED_ORGANISATIONS"; // <--- new
//export const FILTERED_JOBS_BY_ORGANISATIONS = "FILTERED_JOBS_BY_ORGANISATIONS"; // <--- new
export const INCLUBE_JOBS_BY_ORGANISATION = "INCLUBE_JOBS_BY_ORGANISATION";
export const INCLUBE_JOB_BY_ORGANISATION = "INCLUBE_JOB_BY_ORGANISATION";

//JOB TYPES
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES"; // <--- new
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES"; // <--- new
//export const FILTERED_JOBS_BY_JOB_TYPES = "FILTERED_JOBS_BY_JOB_TYPES"; // <--- new
export const INCLUBE_JOB_BY_JOB_TYPES = "INCLUBE_JOB_BY_JOB_TYPES";
