//USER
export const LOGIN_USER = "LOGIN_USER"; // action

//JOBS
export const RECIEVED_JOBS = "RECIEVED_JOBS"; // typo in the video
export const FETCH_JOBS = "FETCH_JOBS"; // <--- new
export const FILTERED_JOBS = "FILTERED_JOBS";

//ORGANISATIONS
export const UNIQUE_ORGANISATIONS = "UNIQUE_ORGANISATIONS"; // <--- new
export const ADD_SELECTED_ORGANISATIONS = "ADD_SELECTED_ORGANISATIONS"; // <--- new
//export const FILTERED_JOBS_BY_ORGANISATIONS = "FILTERED_JOBS_BY_ORGANISATIONS"; // <--- new
export const INCLUBE_JOBS_BY_ORGANISATION = "INCLUBE_JOBS_BY_ORGANISATION";
export const INCLUBE_JOB_BY_ORGANISATION = "INCLUBE_JOB_BY_ORGANISATION";

//JOB TYPES
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES"; // <--- new
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES"; // <--- new
//export const FILTERED_JOBS_BY_JOB_TYPES = "FILTERED_JOBS_BY_JOB_TYPES"; // <--- new
export const INCLUBE_JOB_BY_JOB_TYPES = "INCLUBE_JOB_BY_JOB_TYPES";
